language: ruby
sudo: false

cache:
  bundler: true
  directories:
  - node_modules

env:
  global:
    - OPAL_VERSION="~> 0.10.0"

matrix:
  fast_finish: true

  include:
    - rvm: 2.4.5
      env: RUN=mri_sanity_check
    - rvm: 2.3.8
      env: RUN=mri_sanity_check
    - rvm: 2.5.3
      env: RUN=mri_sanity_check
    - rvm: 2.5.3
      env: RUN=rake_only
    - rvm: 2.5.3
      env: RUNNER=node RUN=rake_only

before_install:
  - "export PATH=`pwd`/node_modules/phantomjs-prebuilt/bin:$PATH"
  - "echo $PATH"
  - phantomjs -v | grep 2.1 || npm install phantomjs-prebuilt # get rate limits from bitbucket download source, so get from NPM if we don't have it already

script:
  - "bundle exec rake $RUN"
